#!/bin/bash

# Update system packages
sudo yum update -y

# Install kubectl
curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin
kubectl version --short --client

# Install eksctl
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
eksctl version

# Create EKS cluster
eksctl create cluster --name Innova-d \
  --region us-east-1 \
  --node-type t2.micro \
  --nodes-min 2 \
  --nodes-max 2 \
  --zones us-east-1a,us-east-1b
